
server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://106.14.141.90:3306/hanger?serverTimezone=GMT%2B8
    username: root
    password: 123456
    platform: mysql
    # 使用阿里巴巴的开源框架druid数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql 8.0.+使用的驱动
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # mapper映射文件地址，这里我在src/main/resouces下新建文件夹mapper
  mapper-locations: classpath*:mapper/*.xml
  # 配置bean扫描目录，也可用注解
  type-aliases-package: classpath*:com.example.hanger.entity